### ISSUE TITLE
Change library name?

### ISSUE THREAD

**Issue by Yash-10** [SforAiDl/jeta#11]
`max` has a name collision with the in-built [`max`](https://docs.python.org/3/library/functions.html#max). Don't know if could be a big problem but certainly, we could change `max` to something else. Ideas? (`metax`, `metajax`, ...) ?

**Comment by veds12** [comment]
Thanks for pointing this out. This can potentially lead to problem which can be worked around but it's better to change the name to avoid confusion. I like `MetAX`.

**Comment by veds12** [comment]
https://pypi.org/search/?q=metax&o=

**Comment by veds12** [comment]
Solved #12
