### ISSUE TITLE
Add a base class for the algorithms

### ISSUE THREAD

**Issue by veds12** [SforAiDl/jeta#23]
Inherit form ABC

**Comment by akagam1** [comment]
so we need to create a class where the class methods are the algorithms that are already implemented (and that will be implemented)?

**Comment by veds12** [comment]
@akagam1 no. The base class will be a skeleton class which will be inherited by all the algorithms.

It will contain methods which are common for all the algorithms (only MAML for now) (for eg. a `train()` method, a `compute_loss()` method, etc.). You do not need to define these methods, just declare them as abstract methods.

Some References:
- [Abstract Base Class in Python](https://www.geeksforgeeks.org/abstract-classes-in-python/)
- [Example of a Base Class for an RL Agent (from GenRL)](https://github.com/SforAiDl/genrl/blob/ce767e43859a65e67d3ec1f7ca59b751b114615f/genrl/agents/deep/base/base.py#L10)

We can continue the discussion on slack (if you have further questions)

**Comment by akagam1** [comment]
can I do this one?

**Comment by veds12** [comment]
Sure
