### ISSUE TITLE
Add a task dataset class and a task sampler

### ISSUE THREAD

**Issue by veds12** [SforAiDl/jeta#24]
Thanks for suggesting @AnirudhM1 and @Devanshu42 !

- We can follow the same structure as learn2learn's [TaskDataset](http://learn2learn.net/docs/learn2learn.data/#learn2learn.data.task_dataset.TaskDataset).
- Number of ways and shots can be passed as parameters to the TaskDataset

**Comment by eigengravy** [comment]
@veds12 can I work on this?

**Comment by veds12** [comment]
Sure, thanks!

**Comment by veds12** [comment]
@eigengravy any updates on this? Let me know if you need any help / want to discuss anything :)

**Comment by eigengravy** [comment]
Opened a draft pr
